# Generated by Django 2.2.4 on 2019-08-30 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ptr', '普通人'), ('sam', '设备负责人'), ('dam', '部门负责人')], default='ptr', max_length=3, verbose_name='角色'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='departments.Department', verbose_name='部门'),
        ),
    ]
