# Generated by Django 2.2.4 on 2019-08-30 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190830_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='number',
            field=models.CharField(default='', max_length=15, verbose_name='学号工号'),
        ),
    ]
