# Generated by Django 2.2.4 on 2019-08-30 09:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('name', models.CharField(max_length=20, verbose_name='建筑楼号')),
                ('campus', models.CharField(choices=[('jm', '金明'), ('ml', '明伦')], default='', max_length=2, verbose_name='所在校区')),
                ('desc', models.CharField(blank=True, max_length=50, null=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '建筑楼号',
                'verbose_name_plural': '建筑楼号',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('name', models.CharField(default='', max_length=50, verbose_name='部门名')),
            ],
            options={
                'verbose_name': '部门信息',
                'verbose_name_plural': '部门信息',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('name', models.CharField(max_length=20, verbose_name='房间号')),
                ('desc', models.CharField(blank=True, max_length=50, null=True, verbose_name='描述')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.Building', verbose_name='所在建筑楼')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='departments.Department', verbose_name='所属部门')),
            ],
            options={
                'verbose_name': '房间号',
                'verbose_name_plural': '房间号',
            },
        ),
    ]
