# Generated by Django 2.2.4 on 2019-08-30 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'verbose_name': '建筑楼', 'verbose_name_plural': '建筑楼'},
        ),
        migrations.AlterField(
            model_name='building',
            name='name',
            field=models.CharField(max_length=20, verbose_name='建筑楼'),
        ),
    ]
