# Generated by Django 2.2.4 on 2019-08-30 09:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('location', models.CharField(blank=True, max_length=254, null=True, verbose_name='存放地点')),
                ('asset_number', models.CharField(blank=True, max_length=254, null=True, verbose_name='资产编号')),
                ('asset_name', models.CharField(blank=True, max_length=254, null=True, verbose_name='资产名称')),
                ('classification', models.CharField(blank=True, max_length=254, null=True, verbose_name='分类号')),
                ('category', models.CharField(blank=True, max_length=254, null=True, verbose_name='分类名称')),
                ('assets_class', models.CharField(blank=True, max_length=254, null=True, verbose_name='国资分类号')),
                ('model', models.CharField(blank=True, max_length=254, null=True, verbose_name='型号')),
                ('specifications', models.CharField(blank=True, max_length=254, null=True, verbose_name='规格')),
                ('purchase_date', models.CharField(blank=True, max_length=254, null=True, verbose_name='购置日期')),
                ('price', models.CharField(blank=True, max_length=254, null=True, verbose_name='单价')),
                ('number', models.CharField(blank=True, max_length=254, null=True, verbose_name='数量')),
                ('total_annex', models.CharField(blank=True, max_length=254, null=True, verbose_name='附件总额')),
                ('total_annex_quantity', models.CharField(blank=True, max_length=254, null=True, verbose_name='附件总数量')),
                ('total_amount', models.CharField(blank=True, max_length=254, null=True, verbose_name='总金额')),
                ('exit_Number', models.CharField(blank=True, max_length=254, null=True, verbose_name='出厂编号')),
                ('date_of_production', models.CharField(blank=True, max_length=254, null=True, verbose_name='出厂日期')),
                ('manufacturer', models.CharField(blank=True, max_length=254, null=True, verbose_name='生产厂家')),
                ('employee', models.CharField(blank=True, max_length=254, null=True, verbose_name='领用人')),
                ('acquisition_date', models.CharField(blank=True, max_length=254, null=True, verbose_name='领用日期')),
                ('present_situation', models.CharField(blank=True, max_length=254, null=True, verbose_name='现状')),
                ('direction_of_use', models.CharField(blank=True, max_length=254, null=True, verbose_name='使用方向')),
                ('user_department', models.CharField(blank=True, max_length=254, null=True, verbose_name='使用单位')),
                ('department', models.CharField(blank=True, max_length=254, null=True, verbose_name='科室')),
                ('bar_code', models.CharField(blank=True, max_length=254, null=True, verbose_name='条码')),
                ('original_value', models.CharField(blank=True, max_length=254, null=True, verbose_name='原值')),
                ('original_quantity', models.CharField(blank=True, max_length=254, null=True, verbose_name='原数量')),
                ('total_original_amount', models.CharField(blank=True, max_length=254, null=True, verbose_name='原总金额')),
                ('original_total_amount_annex', models.CharField(blank=True, max_length=254, null=True, verbose_name='附件原总额')),
                ('original_total_number_annexes', models.CharField(blank=True, max_length=254, null=True, verbose_name='附件原总数量')),
                ('entry_time', models.CharField(blank=True, max_length=254, null=True, verbose_name='录入时间')),
                ('administrator', models.CharField(blank=True, max_length=254, null=True, verbose_name='管理人')),
                ('service_life', models.CharField(blank=True, max_length=254, null=True, verbose_name='使用年限')),
                ('number_of_financial_assets', models.CharField(blank=True, max_length=254, null=True, verbose_name='财政资产编号')),
                ('bill_entry_number', models.CharField(blank=True, max_length=254, null=True, verbose_name='入账单编号')),
                ('state_category', models.CharField(blank=True, max_length=254, null=True, verbose_name='国资大类')),
                ('call_out_number', models.CharField(blank=True, max_length=254, null=True, verbose_name='调出编号')),
                ('original_asset_number', models.CharField(blank=True, max_length=254, null=True, verbose_name='原资产编号')),
                ('provincial_asset_number', models.CharField(blank=True, max_length=254, null=True, verbose_name='省资产编号')),
                ('financial_certificate_number', models.CharField(blank=True, max_length=254, null=True, verbose_name='财务凭证号')),
                ('agent', models.CharField(blank=True, max_length=254, null=True, verbose_name='经办人')),
                ('acceptor', models.CharField(blank=True, max_length=254, null=True, verbose_name='验收人')),
                ('bookkeeper', models.CharField(blank=True, max_length=254, null=True, verbose_name='记账人')),
                ('invoice_number', models.CharField(blank=True, max_length=254, null=True, verbose_name='发票号码')),
                ('financial_classification', models.CharField(blank=True, max_length=254, null=True, verbose_name='财务分类')),
                ('filing_and_registration', models.CharField(blank=True, max_length=254, null=True, verbose_name='备案登记')),
                ('date_of_filing', models.CharField(blank=True, max_length=254, null=True, verbose_name='备案日期')),
                ('account_reconciliation', models.CharField(blank=True, max_length=254, null=True, verbose_name='科目对账')),
                ('accounting_date', models.CharField(blank=True, max_length=254, null=True, verbose_name='记账日期')),
                ('detailed_outlay', models.CharField(blank=True, max_length=254, null=True, verbose_name='经费详目')),
                ('unit_of_measurement', models.CharField(blank=True, max_length=254, null=True, verbose_name='计量单位')),
            ],
            options={
                'verbose_name': '资产固定信息',
                'verbose_name_plural': '资产固定信息',
            },
        ),
    ]
