# Generated by Django 2.2.4 on 2019-08-31 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='contact_number',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='合同编号'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_number',
            field=models.CharField(max_length=254, verbose_name='资产编号'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='location',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='原始存放地点'),
        ),
    ]
