# Generated by Django 2.2.4 on 2019-08-30 09:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Change',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('room_id', models.IntegerField(default='', verbose_name='Room_fk')),
                ('asset_number', models.CharField(default='', max_length=20, verbose_name='资产编号_fk')),
                ('comment', models.CharField(default='', max_length=254, verbose_name='提交备注')),
                ('last_change_id', models.IntegerField(default='', verbose_name='上一次的Change_fk')),
                ('date', models.DateTimeField(verbose_name='修改日期')),
                ('status', models.CharField(choices=[('sy', '使用'), ('wx', '维修'), ('xz', '闲置')], default='', max_length=2, verbose_name='资产状态')),
                ('is_approved', models.BooleanField(default=False, verbose_name='是否通过审核')),
                ('manager_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='通过审核人')),
                ('summit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_asset', to=settings.AUTH_USER_MODEL, verbose_name='提交审核人')),
            ],
            options={
                'verbose_name': '变更记录',
                'verbose_name_plural': '变更记录',
            },
        ),
        migrations.CreateModel(
            name='AssetManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('change_id', models.IntegerField(default='', verbose_name='Change_fk')),
                ('asset_number', models.CharField(default='', max_length=20, verbose_name='资产编号')),
                ('status', models.CharField(choices=[('sy', '使用'), ('wx', '维修'), ('xz', '闲置')], default='', max_length=2, verbose_name='资产状态')),
                ('contract_number', models.CharField(default='', max_length=254, verbose_name='合同编号')),
                ('is_abandoned', models.BooleanField(default=False, verbose_name='是否报废')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='设备负责人')),
            ],
            options={
                'verbose_name': '资产信息',
                'verbose_name_plural': '资产信息',
            },
        ),
    ]
